# February 3, 2020
# Jack Wong (zhaoshan99@gmail.com)



LOG_DEBUG               = 0
LOG_WARNING             = 1
LOG_ERROR               = 2
LOG_FATAL               = 3



APP_ANALYTICS_ID_REPORT_PIG_PROD_OPERATIONS         = 1
APP_ANALYTICS_ID_REPORT_PIG_PROD_WEANING            = 2
APP_ANALYTICS_ID_REPORT_FEED_CONSUMPTION            = 3



BUSINESS_OBJ_ID_USER_REGISTER                       = 1
BUSINESS_OBJ_ID_SEMEN_SUPPLIER                      = 13
BUSINESS_OBJ_ID_FEED_SUPPLIER                       = 14
BUSINESS_OBJ_ID_FEED_BRAND                          = 15



# user.flag bits
FLAG_BIT_USER_IS_ACTIVE                             = 1
FLAG_BIT_USER_EMAIL_VERIFIED                        = 2
FLAG_BIT_USER_MOBILE_NUM_VERIFIED                   = 4
FLAG_BIT_USER_IS_DELETED                            = 8

FLAG_BIT_USER_IS_ACCOUNT_ADMIN                      = 16


MFA_CHANNEL_ID_EMAIL                                = 1
MFA_CHANNEL_ID_PHONE_NUMBER                         = 2

MFA_VERIFICATION_CODE_MIN                           = 100000
MFA_VERIFICATION_CODE_MAX                           = 999999


MFA_SEND_SUCCESS                                    = 0



NUM_MINUTES_EXPIRE_USER_REG_EMAIL_VERIFY            = 5


INS_STATUS_ID_TERMINATED                            = 2


PROD_STATUS_ID_GESTATING                            = 1
PROD_STATUS_ID_TERMINATED                           = 2
PROD_STATUS_ID_NOT_PREGNANT                         = 3
PROD_STATUS_ID_LACTATING                            = 4
PROD_STATUS_ID_WEANING                              = 5
PROD_STATUS_ID_GROWING                              = 6

PROD_STATUS_ID_COMBINED                             = 7
PROD_STATUS_ID_HARVESTED                            = 8
PROD_STATUS_ID_CLOSED                               = 9






PIG_OPERATION_TYPE_GESTATING                        = 1
PIG_OPERATION_TYPE_LACTATING_PIGLETS                = 2
PIG_OPERATION_TYPE_LACTATING_SOW                    = 3
PIG_OPERATION_TYPE_GROWING                          = 4



FEED_TYPE_ID_GESTATING                              = 1
FEED_TYPE_ID_LACTATING                              = 2
FEED_TYPE_ID_BOOSTER                                = 3
FEED_TYPE_ID_PRESTARTER                             = 4
FEED_TYPE_ID_STARTER                                = 5
FEED_TYPE_ID_GROWER                                 = 6
FEED_TYPE_ID_FINISHER                               = 7



DEFAULT_KG_PER_FEED_UNIT = {
    'GESTATING':    50.0,
    'LACTATING':    50.0,
    'BOOSTER':       1.0,
    'PRESTARTER':   25.0,
    'STARTER':      50.0,
    'GROWER':       50.0,
    'FINISHER':     50.0
}



ERROR_DATABASE_ERROR                                = 0x01
ERROR_SERVER_ERROR                                  = 0x02

ERROR_ADDRESS_LEVEL_1_HID                           = 0x08
ERROR_ADDRESS_LEVEL_2_HID                           = 0x09
ERROR_ADDRESS_LEVEL_3_HID                           = 0x0A



ERROR_PIG_PROD_OPS_INVALID_USER_HASHID              = 0x10
ERROR_PIG_PROD_OPS_INVALID_PIG_FARM_HASHID          = 0x11


ERROR_USER_INVALID_USER_HASHID                      = 0x20
ERROR_USER_INVALID_USER_INACTIVE                    = 0x21
ERROR_USER_INVALID_USER_NOT_EMAIL_VERIFIED          = 0x22
ERROR_USER_ALREADY_CONNECTED_TO_ACCOUNT             = 0x23


ERROR_ACCOUNT_INVALID_NAME                          = 0x30
ERROR_ACCOUNT_INVALID_HASHID                        = 0x31

ERROR_ACCOUNT_INVALID_FEED_SUPPLIER_HASHID          = 0x35
ERROR_ACCOUNT_INVALID_SEMEN_SUPPLIER_HASHID         = 0x36



ERROR_ACCOUNT_REQUEST_INVALID_USER_HASHID           = 0x40
ERROR_ACCOUNT_REQUEST_INVALID_ACCOUNT_HASHID        = 0x41
ERROR_ACCOUNT_REQUEST_INVALID_HASHID                = 0x42




ERROR_PIG_FARM_INVALID_NAME                         = 0x40
ERROR_PIG_FARM_INVALID_HASHID                       = 0x41
ERROR_PIG_FARM_INVALID_ACCOUNT_HASHID               = 0x42


ERROR_PIG_FARM_STAFF_INVALID_NAME                   = 0x49
ERROR_PIG_FARM_STAFF_INVALID_USER_HASHID            = 0x4A
ERROR_PIG_FARM_STAFF_INVALID_PIG_FARM_HASHID        = 0x4B
ERROR_PIG_FARM_STAFF_INVALID_HASHID                 = 0x4C



ERROR_SOW_BOAR_INVALID_USER_HASHID                  = 0x50
ERROR_SOW_BOAR_INVALID_PIG_FARM_HASHID              = 0x51
ERROR_SOW_BOAR_INVALID_SOW_BOAR_NUMBER              = 0x52
ERROR_SOW_BOAR_INVALID_SOW_BOAR_NAME                = 0x53
ERROR_SOW_BOAR_NO_SOW_BOAR_NUMBER_AND_NAME          = 0x54


ERROR_ACCOUNT_PIG_OPS_INVALID_USER_HASHID           = 0x60
ERROR_ACCOUNT_PIG_OPS_INVALID_HASHID                = 0x61

ERROR_ACCOUNT_PIG_OPS_INVALID_NAME                  = 0x62
ERROR_ACCOUNT_PIG_OPS_INVALID_OPERATION_TYPE        = 0x63
ERROR_ACCOUNT_PIG_OPS_INVALID_NUMDAYS               = 0x64
ERROR_ACCOUNT_PIG_OPS_INVALID_ACCOUNT_HASHID        = 0x65


ERROR_PIG_RACE_LINE_INVALID_USER_HASHID             = 0x70
ERROR_PIG_RACE_LINE_INVALID_HASHID                  = 0x71

ERROR_PIG_RACE_LINE_INVALID_NAME                    = 0x72


ERROR_FEED_BRAND_INVALID_USER_HASHID                = 0x79
ERROR_FEED_BRAND_INVALID_HASHID                     = 0x7A

ERROR_FEED_BRAND_INVALID_NAME                       = 0x7B





ERROR_SEMEN_SUPPLIER_INVALID_USER_HASHID            = 0x80
ERROR_SEMEN_SUPPLIER_INVALID_HASHID                 = 0x81

ERROR_SEMEN_SUPPLIER_INVALID_NAME                   = 0x82
ERROR_SEMEN_SUPPLIER_INVALID_ADDRESS_LEVEL_1        = 0x83
ERROR_SEMEN_SUPPLIER_INVALID_ADDRESS_LEVEL_2        = 0x84





ERROR_SEMEN_SOURCE_INVALID_USER_HASHID              = 0x90
ERROR_SEMEN_SOURCE_INVALID_HASHID                   = 0x91

ERROR_SEMEN_SOURCE_INVALID_PIG_FARM_HASHID          = 0x92
ERROR_SEMEN_SOURCE_INVALID_BOAR_HASHID              = 0x93
ERROR_SEMEN_SOURCE_INVALID_SEMEN_SUPPLIER_HASHID    = 0x94
ERROR_SEMEN_SOURCE_INVALID_PIG_RACE_LINE_HASHID     = 0x95




ERROR_PIG_PROD_INVALID_USER_HASHID                  = 0xA0
ERROR_PIG_PROD_INVALID_HASHID                       = 0xA1

ERROR_PIG_PROD_INVALID_SOW_HASHID                   = 0xA2
ERROR_PIG_PROD_INVALID_BOAR_HASHID                  = 0xA3
ERROR_PIG_PROD_INVALID_SEMEN_SOURCE_HASHID          = 0xA4
ERROR_PIG_PROD_INVALID_INSEM_STAFF_HASHID           = 0xA5
ERROR_PIG_PROD_INVALID_BIRTH_STAFF_HASHID           = 0xA6
ERROR_PIG_PROD_INVALID_PIG_FARM_HASHID              = 0xA7
ERROR_PIG_PROD_INVALID_PROD_STATUS_HASHID           = 0xA8


ERROR_PIG_PROD_NOTES_INVALID_USER_HASHID            = 0xB0
ERROR_PIG_PROD_NOTES_INVALID_HASHID                 = 0xB1

ERROR_PIG_PROD_NOTES_INVALID_PIG_PROD_HASHID        = 0xB2


ERROR_PROD_GESTATING_OPS_INVALID_USER_HASHID        = 0xB8
ERROR_PROD_GESTATING_OPS_INVALID_HASHID             = 0xB9

ERROR_PROD_GESTATING_OPS_INVALID_STAFF_HASHID       = 0xBA


ERROR_PROD_LACTATING_OPS_INVALID_USER_HASHID        = 0xC0
ERROR_PROD_LACTATING_OPS_INVALID_HASHID             = 0xC1

ERROR_PROD_LACTATING_OPS_INVALID_STAFF_HASHID       = 0xC2


ERROR_FEED_BUY_INVALID_USER_HASHID                  = 0xC8
ERROR_FEED_BUY_INVALID_HASHID                       = 0xC9

ERROR_FEED_BUY_INVALID_PIG_PROD_HASHID              = 0xCA
ERROR_FEED_BUY_INVALID_FEED_TYPE_HASHID             = 0xCB
ERROR_FEED_BUY_INVALID_FEED_BRAND_HASHID            = 0xCC


ERROR_FEED_SUPPLIER_INVALID_USER_HASHID             = 0xD0
ERROR_FEED_SUPPLIER_INVALID_HASHID                  = 0xD1

ERROR_FEED_SUPPLIER_INVALID_NAME                    = 0xD2
ERROR_FEED_SUPPLIER_INVALID_ADDRESS_LEVEL_1         = 0xD3
ERROR_FEED_SUPPLIER_INVALID_ADDRESS_LEVEL_2         = 0xD4
ERROR_FEED_SUPPLIER_INVALID_ADDRESS_LEVEL_3         = 0xD5



ERROR_PIG_DEAD_INVALID_USER_HASHID                  = 0xE0
ERROR_PIG_DEAD_INVALID_HASHID                       = 0xE1

ERROR_PIG_DEAD_INVALID_PIG_PROD_HASHID              = 0xE2
ERROR_PIG_DEAD_INVALID_PROD_GROUP_HASHID            = 0xE3
ERROR_PIG_DEAD_INVALID_PIG_DEAD_TYPE_HASHID         = 0xE4
