# February 3, 2020
# Jack Wong (zhaoshan99@gmail.com)



LOG_DEBUG               = 0
LOG_WARNING             = 1
LOG_ERROR               = 2
LOG_FATAL               = 3



APP_ANALYTICS_ID_REPORT_PIG_PROD_OPERATIONS         = 1
APP_ANALYTICS_ID_REPORT_PIG_PROD_WEANING            = 2
APP_ANALYTICS_ID_REPORT_FEED_CONSUMPTION            = 3



BUSINESS_OBJ_ID_USER_REGISTER                       = 1
BUSINESS_OBJ_ID_SEMEN_SUPPLIER                      = 13
BUSINESS_OBJ_ID_FEED_SUPPLIER                       = 14
BUSINESS_OBJ_ID_FEED_BRAND                          = 15






MFA_CHANNEL_ID_EMAIL                                = 1
MFA_CHANNEL_ID_PHONE_NUMBER                         = 2

MFA_VERIFICATION_CODE_MIN                           = 100000
MFA_VERIFICATION_CODE_MAX                           = 999999


MFA_SEND_SUCCESS                                    = 0



NUM_MINUTES_EXPIRE_USER_REG_EMAIL_VERIFY            = 5


INS_STATUS_ID_TERMINATED                            = 2


ACC_BILL_STATUS = {
    'NEW':      1,
    'OVERDUE':  2,
    'PAID':     3
}


SOW_STATUS_GROWING                                  = 1
SOW_STATUS_GESTATING                                = 2
SOW_STATUS_LACTATING                                = 3
SOW_STATUS_WEANING                                  = 4




PROD_STATUS_ID_GESTATING                            = 1
PROD_STATUS_ID_TERMINATED                           = 2
PROD_STATUS_ID_NOT_PREGNANT                         = 3
PROD_STATUS_ID_LACTATING                            = 4
PROD_STATUS_ID_WEANING                              = 5
PROD_STATUS_ID_GROWING                              = 6

PROD_STATUS_ID_COMBINED                             = 7
PROD_STATUS_ID_HARVESTED                            = 8
PROD_STATUS_ID_CLOSED                               = 9


PIG_PROD_TYPE = {
    'GESTATING':        1,
    'LACTATING':        2,
    'FATTENING':        4
}





PIG_OPERATION_TYPE_GESTATING                        = 1
PIG_OPERATION_TYPE_LACTATING_PIGLETS                = 2
PIG_OPERATION_TYPE_LACTATING_SOW                    = 3
PIG_OPERATION_TYPE_GILT                             = 4
PIG_OPERATION_TYPE_WEANING_SOW                      = 5

# This is not saved in database
PIG_OPERATION_TYPE_LACTATING_COMBINED               = 10


FEED_TYPE_ID_GESTATING                              = 1
FEED_TYPE_ID_LACTATING                              = 2
FEED_TYPE_ID_BOOSTER                                = 3
FEED_TYPE_ID_PRESTARTER                             = 4
FEED_TYPE_ID_STARTER                                = 5
FEED_TYPE_ID_GROWER                                 = 6
FEED_TYPE_ID_FINISHER                               = 7



DEFAULT_KG_PER_FEED_UNIT = {
    'GESTATING':    50.0,
    'LACTATING':    50.0,
    'BOOSTER':       1.0,
    'PRESTARTER':   25.0,
    'STARTER':      50.0,
    'GROWER':       50.0,
    'FINISHER':     50.0
}



REQUEST_ACCESS_DENIED    = "Access denied"




ERROR_DATABASE_ERROR                                = 0x01
ERROR_SERVER_ERROR                                  = 0x02

ERROR_USER_EMAIL                                    = 0x03
ERROR_USER_INACTIVE                                 = 0x04




ERROR_ACCOUNT_DISABLED                              = 0x08
ERROR_ACCOUNT_BILL_OVERDUE                          = 0x09





ERROR_ADDRESS_COUNTRY_HID                           = 0x0A
ERROR_ADDRESS_LEVEL_1_HID                           = 0x0B
ERROR_ADDRESS_LEVEL_2_HID                           = 0x0C
ERROR_ADDRESS_LEVEL_3_HID                           = 0x0D



ERROR_PIG_PROD_OPS_INVALID_USER_HASHID              = 0x10
ERROR_PIG_PROD_OPS_INVALID_PIG_FARM_HASHID          = 0x11


ERROR_USER_INVALID_USER_HASHID                      = 0x20
ERROR_USER_INVALID_USER_INACTIVE                    = 0x21
ERROR_USER_INVALID_USER_NOT_EMAIL_VERIFIED          = 0x22
ERROR_USER_ALREADY_CONNECTED_TO_ACCOUNT             = 0x23


ERROR_ACCOUNT_INVALID_NAME                          = 0x30
ERROR_ACCOUNT_INVALID_HASHID                        = 0x31

ERROR_ACCOUNT_INVALID_FEED_SUPPLIER_HASHID          = 0x35
ERROR_ACCOUNT_INVALID_SEMEN_SUPPLIER_HASHID         = 0x36



ERROR_USER_REQUEST_INVALID_USER_HASHID              = 0x38
ERROR_USER_REQUEST_INVALID_ACCOUNT_HASHID           = 0x39
ERROR_USER_REQUEST_INVALID_HASHID                   = 0x3A




ERROR_PIG_FARM_INVALID_NAME                         = 0x40
ERROR_PIG_FARM_INVALID_HASHID                       = 0x41
ERROR_PIG_FARM_INVALID_ACCOUNT_HASHID               = 0x42


ERROR_PIG_FARM_STAFF_INVALID_NAME                   = 0x49
ERROR_PIG_FARM_STAFF_INVALID_USER_HASHID            = 0x4A
ERROR_PIG_FARM_STAFF_INVALID_PIG_FARM_HASHID        = 0x4B
ERROR_PIG_FARM_STAFF_INVALID_HASHID                 = 0x4C



ERROR_SOW_BOAR_INVALID_USER_HASHID                  = 0x50
ERROR_SOW_BOAR_INVALID_HASHID                       = 0x51
ERROR_SOW_BOAR_INVALID_PIG_FARM_HASHID              = 0x52
ERROR_SOW_BOAR_INVALID_SOW_BOAR_NUMBER              = 0x53
ERROR_SOW_BOAR_INVALID_SOW_BOAR_NAME                = 0x54
ERROR_SOW_BOAR_INVALID_PARENT_SOW_HASHID            = 0x55
ERROR_SOW_BOAR_INVALID_PARENT_BOAR_HASHID           = 0x56
ERROR_SOW_BOAR_NO_SOW_BOAR_NUMBER_OR_NAME           = 0x57



ERROR_ACCOUNT_PIG_OPS_INVALID_USER_HASHID           = 0x60
ERROR_ACCOUNT_PIG_OPS_INVALID_HASHID                = 0x61

ERROR_ACCOUNT_PIG_OPS_INVALID_NAME                  = 0x62
ERROR_ACCOUNT_PIG_OPS_INVALID_OPERATION_TYPE        = 0x63
ERROR_ACCOUNT_PIG_OPS_INVALID_NUMDAYS               = 0x64
ERROR_ACCOUNT_PIG_OPS_INVALID_ACCOUNT_HASHID        = 0x65


ERROR_PIG_RACE_LINE_INVALID_USER_HASHID             = 0x70
ERROR_PIG_RACE_LINE_INVALID_HASHID                  = 0x71

ERROR_PIG_RACE_LINE_INVALID_NAME                    = 0x72


ERROR_FEED_BRAND_INVALID_USER_HASHID                = 0x79
ERROR_FEED_BRAND_INVALID_HASHID                     = 0x7A

ERROR_FEED_BRAND_INVALID_NAME                       = 0x7B





ERROR_SUPPLIER_INVALID_USER_HASHID                  = 0x80
ERROR_SUPPLIER_INVALID_HASHID                       = 0x81

ERROR_SUPPLIER_INVALID_NAME                         = 0x82
ERROR_SUPPLIER_INVALID_ADDRESS_LEVEL_1              = 0x83
ERROR_SUPPLIER_INVALID_ADDRESS_LEVEL_2              = 0x84
ERROR_SUPPLIER_INVALID_ADDRESS_LEVEL_3              = 0x85
ERROR_SUPPLIER_MUST_HAVE_AT_LEAST_SUPPLIER_FLAG     = 0x86




ERROR_ACCOUNT_SELECTION_INVALID_USER_HASHID         = 0x90
ERROR_ACCOUNT_SELECTION_INVALID_HASHID              = 0x91

ERROR_ACCOUNT_SELECTION_INVALID_FEED_SUPPLIER_HASHID  = 0x92
ERROR_ACCOUNT_SELECTION_INVALID_SEMEN_SUPPLIER_HASHID = 0x93

ERROR_ACCOUNT_SELECTION_NOTHING_SELECTED             = 0x94



ERROR_PIG_PROD_INVALID_USER_HASHID                  = 0xA0
ERROR_PIG_PROD_INVALID_HASHID                       = 0xA1

ERROR_PIG_PROD_INVALID_SOW_HASHID                   = 0xA2
ERROR_PIG_PROD_INVALID_BOAR_HASHID                  = 0xA3
ERROR_PIG_PROD_INVALID_SEMEN_SUPPLIER_HASHID        = 0xA4
ERROR_PIG_PROD_INVALID_SEMEN_HASHID                 = 0xA5
ERROR_PIG_PROD_INVALID_AI_BOAR_HASHID               = 0xA6

ERROR_PIG_PROD_INVALID_INSEM_STAFF_HASHID           = 0xA7
ERROR_PIG_PROD_INVALID_BIRTH_STAFF_HASHID           = 0xA8
ERROR_PIG_PROD_INVALID_PIG_FARM_HASHID              = 0xA9
ERROR_PIG_PROD_INVALID_PROD_STATUS_HASHID           = 0xAA


ERROR_PIG_PROD_NOTES_INVALID_USER_HASHID            = 0xB0
ERROR_PIG_PROD_NOTES_INVALID_HASHID                 = 0xB1
ERROR_PIG_PROD_NOTES_INVALID_PIG_PROD_HASHID        = 0xB2
ERROR_PIG_PROD_NOTES_INVALID_SOW_BOAR_HASHID        = 0xB3
ERROR_PIG_PROD_NOTES_NO_VALID_KEY                   = 0xB4


ERROR_PROD_GESTATING_OPS_INVALID_USER_HASHID        = 0xB8
ERROR_PROD_GESTATING_OPS_INVALID_HASHID             = 0xB9

ERROR_PROD_GESTATING_OPS_INVALID_STAFF_HASHID       = 0xBA


ERROR_PROD_LACTATING_OPS_INVALID_USER_HASHID        = 0xC0
ERROR_PROD_LACTATING_OPS_INVALID_HASHID             = 0xC1

ERROR_PROD_LACTATING_OPS_INVALID_STAFF_HASHID       = 0xC2


ERROR_FEED_BUY_INVALID_USER_HASHID                  = 0xC8
ERROR_FEED_BUY_INVALID_HASHID                       = 0xC9

ERROR_FEED_BUY_INVALID_PIG_PROD_HASHID              = 0xCA
ERROR_FEED_BUY_INVALID_FEED_TYPE_HASHID             = 0xCB
ERROR_FEED_BUY_INVALID_FEED_BRAND_HASHID            = 0xCC


ERROR_FEED_SUPPLIER_INVALID_USER_HASHID             = 0xD0
ERROR_FEED_SUPPLIER_INVALID_HASHID                  = 0xD1

ERROR_FEED_SUPPLIER_INVALID_NAME                    = 0xD2
ERROR_FEED_SUPPLIER_INVALID_ADDRESS_LEVEL_1         = 0xD3
ERROR_FEED_SUPPLIER_INVALID_ADDRESS_LEVEL_2         = 0xD4
ERROR_FEED_SUPPLIER_INVALID_ADDRESS_LEVEL_3         = 0xD5
ERROR_FEED_SUPPLIER_INVALID_ACCOUNT_HASHID          = 0xD6


ERROR_PIG_DEAD_INVALID_USER_HASHID                  = 0xE0
ERROR_PIG_DEAD_INVALID_HASHID                       = 0xE1

ERROR_PIG_DEAD_INVALID_PIG_PROD_HASHID              = 0xE2
ERROR_PIG_DEAD_INVALID_PROD_GROUP_HASHID            = 0xE3
ERROR_PIG_DEAD_INVALID_PIG_DEAD_TYPE_HASHID         = 0xE4



ERROR_MEDVAC_BRAND_INVALID_USER_HASHID              = 0xF0
ERROR_MEDVAC_BRAND_INVALID_HASHID                   = 0xF1

ERROR_MEDVAC_BRAND_INVALID_NAME                     = 0xF2


ERROR_ACCOUNT_MEDVAC_INVALID_USER_HASHID            = 0xF8
ERROR_ACCOUNT_MEDVAC_INVALID_HASHID                 = 0xF9

ERROR_ACCOUNT_MEDVAC_INVALID_ACCOUNT_HASHID         = 0xFA
ERROR_ACCOUNT_MEDVAC_INVALID_NAME                   = 0xFB


ERROR_PIG_MEDVAC_INVALID_USER_HASHID                = 0x100
ERROR_PIG_MEDVAC_INVALID_HASHID                     = 0x101

ERROR_PIG_MEDVAC_SOW_BOAR_HASHID                    = 0x102
ERROR_PIG_MEDVAC_INVALID_NAME                       = 0x103
ERROR_PIG_MEDVAC_INVALID_PIG_PROD_HASHID            = 0x104
ERROR_PIG_MEDVAC_INVALID_PIG_PROD_PIG_OPS_HASHID    = 0x105
ERROR_PIG_MEDVAC_INVALID_HEALTH_ISSUE_HASHID        = 0x106
ERROR_PIG_MEDVAC_INVALID_STAFF_HASHID               = 0x107
ERROR_PIG_MEDVAC_INVALID_MEDVAC_BRAND_HASHID        = 0x108
ERROR_PIG_MEDVAC_INVALID_MEDVAC_TYPE_HASHID         = 0x109
ERROR_PIG_MEDVAC_INVALID_ACC_MEDVAC_HASHID          = 0x10A
ERROR_PIG_MEDVAC_NO_VALID_KEY                       = 0x10B


ERROR_SEMEN_SUPPLIER_SEMEN_INVALID_USER_HASHID      = 0x110
ERROR_SEMEN_SUPPLIER_SEMEN_HASHID                   = 0x111

ERROR_SEMEN_SUPPLIER_SEMEN_INVALID_NAME             = 0x112



ERROR_PF_FEED_BUY_INVALID_USER_HASHID               = 0x100
ERROR_PF_FEED_BUY_INVALID_HASHID                    = 0x101

ERROR_PF_FEED_BUY_INVALID_PIG_FARM_HASHID           = 0x102
ERROR_PF_FEED_BUY_INVALID_FEED_SUPPLIER_HASHID      = 0x103


ERROR_PF_FEED_BUY_ITEM_INVALID_USER_HASHID          = 0x100
ERROR_PF_FEED_BUY_ITEM_INVALID_HASHID               = 0x101
ERROR_PF_FEED_BUY_ITEM_INVALID_FEED_BUY_HASHID      = 0x10A
ERROR_PF_FEED_BUY_ITEM_INVALID_FEED_TYPE_HASHID     = 0x10B
ERROR_PF_FEED_BUY_ITEM_INVALID_FEED_BRAND_HASHID    = 0x10C


ERROR_PIG_PROD_FEED_INVALID_USER_HASHID             = 0x120 
ERROR_PIG_PROD_FEED_INVALID_HASHID                  = 0x121

ERROR_PIG_PROD_FEED_INVALID_PIG_PROD_HASHID         = 0x122
ERROR_PIG_PROD_FEED_INVALID_PF_FEED_BUY_HASHID      = 0x123



ERROR_FEED_BALANCE_INVALID_USER_HASHID              = 0x128
ERROR_FEED_BALANCE_INVALID_HASHID                   = 0x129

ERROR_FEED_BALANCE_INVALID_PIG_FARM_HASHID          = 0x12A
ERROR_FEED_BALANCE_INVALID_PIG_PROD_HASHID          = 0x12B
ERROR_FEED_BALANCE_INVALID_PROD_GROUP_HASHID        = 0x12C




ERROR_PIG_DEAD_INVALID_USER_HASHID                  = 0x130
ERROR_PIG_DEAD_INVALID_HASHID                       = 0x131

ERROR_PIG_DEAD_INVALID_PIG_FARM_HASHID              = 0x132
ERROR_PIG_DEAD_INVALID_PIG_PROD_HASHID              = 0x133
ERROR_PIG_DEAD_NO_VALID_KEY                         = 0x134


ERROR_PRODUCTION_HARVEST_INVALID_USER_HASHID        = 0x140
ERROR_PRODUCTION_HARVEST_INVALID_HASHID             = 0x141

ERROR_PRODUCTION_HARVEST_INVALID_TYPE_HASHID        = 0x142
